### ISSUE TITLE
Is "@sender" column ALWAYS part of the "From" column in message list pane?

### ISSUE THREAD

**Issue by pstein** [lkosson/full-address-column#26]
As far as I can see the "@sender" column (in message list pane) always contains the senders emails address.
But the "From" column contains the senders email address too.

Is there any scenario where the email addresses in the two column differ?

If yes: What sense does the "@sender" column make if I already use "From" column?
There would be no new additional information.

Does the same apply to "Recipient" and "@recipient" column?

Can I somehow tell TB to show only Names in "From" and "Recipient" column without email addresses?

**Comment by lkosson** [comment]
This add-on addresses mostly issue from pre-115 TB, where there was no way to display raw sender or recipient e-mail address. Since TB 115, you can change format of the "From" column to display either e-mail address, name or both, and additionally you can decide whether to show names for all messages or only for senders from your address book.

Even in TB 115+, without this add-on you can't have both display name and real address shown in message list with clear demarcation between them to see at first glance which one is which. You can have either of them (with the other one missing) or a mix of both in one column.

I personally have "From" column set up to always show display name and "Sender (@)" column to always show real e-mail address.

**Comment by pstein** [comment]
Thank you for clarification
